---
name: Concurrent Search UTs and ITs

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # precommit on ubuntu-latest is run as a part of the gradle-check workflow
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        if: always()
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build the repo
        if: always()
        run: |
          ./gradlew assemble -x :distribution:docker:buildArm64DockerImage -x :distribution:docker:buildDockerImage -x :distribution:docker:buildPpc64leDockerImage -x :distribution:docker:docker-export:exportDockerImage -x :distribution:docker:buildS390xDockerImage -x :distribution:docker:docker-ppc64le-export:exportDockerImage -x :distribution:docker:docker-s390x-export:exportDockerImage
      - name: Run Gradle unit tests
        if: always()
        run: |
          ./gradlew test -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
      - name: Run Gradle integration tests
        if: always()
        run: |
          ./gradlew internalClusterTest --parallel -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
