name: Sync labels
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize labels
        uses: julbme/gh-action-manage-label@v1
        with:
          from: https://raw.github.com/sohami/.github/tree/main/.github/config/labels.json
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
